import React, { useState } from 'react';
import { Scan, Image, FileText, Upload, Plus, Search, Eye, X, Brain, Activity, Baby, Eye as EyeIcon, Heart, Loader2, AlertTriangle, CheckCircle, Info, ChevronDown, ChevronUp } from 'lucide-react';
import { analyzeChestXRay, analyzeCTScan, analyzeMRI, analyzeMammography, analyzeRetinalImaging } from '../services/aiService';
import {
  ChestXRayAnalysisResult,
  CTScanAnalysisResult,
  MRIAnalysisResult,
  MammographyAnalysisResult,
  RetinalImagingAnalysisResult
} from '../types';

interface ScanRequest {
  id: string;
  patientName: string;
  modality: 'X-Ray' | 'MRI' | 'CT Scan' | 'Ultrasound' | 'Mammography' | 'Retinal';
  bodyPart: string;
  doctor: string;
  date: string;
  status: 'Scheduled' | 'Imaging' | 'Reviewing' | 'Finalized';
  imageCount: number;
}

type AIAnalysisResult = ChestXRayAnalysisResult | CTScanAnalysisResult | MRIAnalysisResult | MammographyAnalysisResult | RetinalImagingAnalysisResult | null;

const Radiology: React.FC = () => {
  const [requests, setRequests] = useState<ScanRequest[]>([
    { id: 'RAD-001', patientName: 'John Doe', modality: 'X-Ray', bodyPart: 'Chest PA', doctor: 'Dr. Smith', date: '2024-03-15', status: 'Finalized', imageCount: 2 },
    { id: 'RAD-002', patientName: 'Jane Smith', modality: 'MRI', bodyPart: 'Brain', doctor: 'Dr. Chen', date: '2024-03-15', status: 'Imaging', imageCount: 0 },
    { id: 'RAD-003', patientName: 'Robert Brown', modality: 'CT Scan', bodyPart: 'Abdomen', doctor: 'Dr. Wilson', date: '2024-03-15', status: 'Reviewing', imageCount: 150 },
    { id: 'RAD-004', patientName: 'Mary Johnson', modality: 'Mammography', bodyPart: 'Bilateral', doctor: 'Dr. Davis', date: '2024-03-15', status: 'Reviewing', imageCount: 4 },
    { id: 'RAD-005', patientName: 'James Wilson', modality: 'Retinal', bodyPart: 'Fundus', doctor: 'Dr. Martinez', date: '2024-03-15', status: 'Finalized', imageCount: 2 },
  ]);

  const [showViewer, setShowViewer] = useState(false);
  const [selectedScan, setSelectedScan] = useState<ScanRequest | null>(null);
  const [aiAnalysis, setAiAnalysis] = useState<AIAnalysisResult>(null);
  const [aiLoading, setAiLoading] = useState(false);
  const [showAIAnalysis, setShowAIAnalysis] = useState(false);
  const [showReport, setShowReport] = useState(false);
  const [reportText, setReportText] = useState('');
  const [activeTab, setActiveTab] = useState<'list' | 'viewer' | 'ai'>('list');

  const generateReport = () => {
    if (!aiAnalysis) return;

    const today = new Date().toLocaleDateString();
    let text = `RADIOLOGY REPORT\nDate: ${today}\nPatient: ${selectedScan?.patientName}\nModality: ${selectedScan?.modality}\nBody Part: ${selectedScan?.bodyPart}\n----------------------------------------\n\n`;

    text += `IMPRESSION:\n${aiAnalysis.overallImpression}\n\n`;
    text += `CONFIDENCE: ${Math.round(aiAnalysis.confidence * 100)}%\n\n`;

    text += `FINDINGS:\n`;
    if ('abnormalities' in aiAnalysis) {
      const abnormalities = (aiAnalysis as any).abnormalities?.filter((a: any) => a.present);
      if (abnormalities?.length > 0) {
        abnormalities.forEach((a: any) => {
          text += `- ${a.type}: ${a.description}\n`;
        });
      } else {
        text += `- No significant abnormalities detected.\n`;
      }
    }

    // Add specific findings based on modality
    if ('biRadsAssessment' in aiAnalysis) {
      text += `- BI-RADS Category: ${(aiAnalysis as any).biRadsAssessment.category}\n`;
    }

    text += `\nRECOMMENDATIONS:\n`;
    aiAnalysis.recommendations.forEach(rec => {
      text += `- ${rec.recommendation} (${rec.timeframe})\n`;
    });

    text += `\n----------------------------------------\n`;
    text += `Report generated by AI Assistant. Verified by: _________________`;

    setReportText(text);
    setShowReport(true);
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'Finalized': return 'bg-success-light text-success-dark';
      case 'Reviewing': return 'bg-info-light text-info-dark';
      case 'Imaging': return 'bg-warning-light text-warning-dark';
      default: return 'bg-background-tertiary text-foreground-secondary';
    }
  };

  const getModalityIcon = (modality: string) => {
    switch (modality) {
      case 'MRI': return <Brain className="text-purple-500" size={18} />;
      case 'CT Scan': return <Scan className="text-blue-500" size={18} />;
      case 'X-Ray': return <Image className="text-teal-500" size={18} />;
      case 'Mammography': return <Heart className="text-pink-500" size={18} />;
      case 'Retinal': return <EyeIcon className="text-amber-500" size={18} />;
      case 'Ultrasound': return <Baby className="text-cyan-500" size={18} />;
      default: return <Scan className="text-foreground-muted" size={18} />;
    }
  };

  const openViewer = (scan: ScanRequest) => {
    setSelectedScan(scan);
    setShowViewer(true);
    setAiAnalysis(null);
    setShowAIAnalysis(false);
    setActiveTab('viewer');
  };

  const runAIAnalysis = async () => {
    if (!selectedScan) return;

    setAiLoading(true);
    setShowAIAnalysis(true);
    setActiveTab('ai');

    try {
      let result: AIAnalysisResult = null;

      // Simulate image data (in real app, this would be actual image data)
      const mockImageData = 'base64_encoded_image_data';

      switch (selectedScan.modality) {
        case 'X-Ray':
          if (selectedScan.bodyPart.toLowerCase().includes('chest')) {
            const response = await analyzeChestXRay({
              imageData: mockImageData,
              patientInfo: {
                age: 45,
                gender: 'Male',
                clinicalIndication: 'Chest pain evaluation'
              }
            });
            result = response.data || null;
          }
          break;
        case 'CT Scan':
          const ctResponse = await analyzeCTScan({
            imageData: mockImageData,
            scanType: selectedScan.bodyPart.toLowerCase().includes('brain') ? 'head' :
              selectedScan.bodyPart.toLowerCase().includes('chest') ? 'chest' : 'abdomen',
            contrastUsed: true,
            patientInfo: {
              age: 52,
              gender: 'Male',
              clinicalIndication: 'Abdominal pain evaluation'
            }
          });
          result = ctResponse.data || null;
          break;
        case 'MRI':
          const mriResponse = await analyzeMRI({
            imageData: mockImageData,
            scanType: selectedScan.bodyPart.toLowerCase().includes('brain') ? 'brain' :
              selectedScan.bodyPart.toLowerCase().includes('spine') ? 'spine' : 'joint',
            sequences: ['T1', 'T2', 'FLAIR'],
            contrastUsed: false,
            patientInfo: {
              age: 38,
              gender: 'Female',
              clinicalIndication: 'Headache evaluation'
            }
          });
          result = mriResponse.data || null;
          break;
        case 'Mammography':
          const mammographyResponse = await analyzeMammography({
            imageData: mockImageData,
            views: ['CC', 'MLO'],
            laterality: 'bilateral',
            patientInfo: {
              age: 48,
              gender: 'Female',
              clinicalIndication: 'Screening mammography'
            }
          });
          result = mammographyResponse.data || null;
          break;
        case 'Retinal':
          const retinalResponse = await analyzeRetinalImaging({
            imageData: mockImageData,
            imagingType: 'fundus_photography',
            laterality: 'bilateral',
            patientInfo: {
              age: 55,
              diabetesStatus: 'type2',
              hypertension: true
            }
          });
          result = retinalResponse.data || null;
          break;
      }

      setAiAnalysis(result);
    } catch (error) {
      console.error('AI Analysis error:', error);
    } finally {
      setAiLoading(false);
    }
  };

  const renderConfidenceBadge = (confidence: number) => {
    const percentage = Math.round(confidence * 100);
    const color = percentage >= 90 ? 'bg-success-light text-success-dark' :
      percentage >= 70 ? 'bg-warning-light text-warning-dark' :
        'bg-danger-light text-danger-dark';
    return (
      <span className={`px-2 py-1 rounded-full text-xs font-medium ${color}`}>
        {percentage}% confidence
      </span>
    );
  };

  const renderChestXRayAnalysis = (analysis: ChestXRayAnalysisResult) => (
    <div className="space-y-4">
      <div className="bg-gradient-to-r from-teal-50 to-cyan-50 dark:from-teal-900/20 dark:to-cyan-900/20 p-4 rounded-lg border border-teal-200 dark:border-teal-800">
        <h4 className="font-semibold text-teal-800 dark:text-teal-300 mb-2">Overall Impression</h4>
        <p className="text-foreground-primary">{analysis.overallImpression}</p>
        <div className="mt-2 flex items-center gap-2">
          {renderConfidenceBadge(analysis.confidence)}
        </div>
      </div>

      <div className="grid grid-cols-2 gap-4">
        <div className="bg-background-elevated p-4 rounded-lg border border-border">
          <h5 className="font-medium text-foreground-primary mb-3 flex items-center gap-2">
            <Activity className="text-red-500" size={18} />
            Cardiac Analysis
          </h5>
          <div className="space-y-2 text-sm">
            <div className="flex justify-between">
              <span className="text-foreground-secondary">Cardiothoracic Ratio:</span>
              <span className="font-medium text-foreground-primary">{analysis.cardiacAnalysis.cardiothoracicRatio}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-foreground-secondary">Heart Size:</span>
              <span className="font-medium capitalize text-foreground-primary">{analysis.cardiacAnalysis.heartSize.replace('_', ' ')}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-foreground-secondary">Cardiomegaly:</span>
              <span className={`font-medium ${analysis.cardiacAnalysis.cardiomegaly ? 'text-red-600' : 'text-green-600'}`}>
                {analysis.cardiacAnalysis.cardiomegaly ? 'Present' : 'Absent'}
              </span>
            </div>
          </div>
        </div>

        <div className="bg-background-elevated p-4 rounded-lg border border-border">
          <h5 className="font-medium text-foreground-primary mb-3 flex items-center gap-2">
            <Image className="text-blue-500" size={18} />
            Lung Analysis
          </h5>
          <div className="space-y-2 text-sm">
            <div className="flex justify-between">
              <span className="text-foreground-secondary">Lung Fields:</span>
              <span className="font-medium capitalize text-foreground-primary">{analysis.lungAnalysis.lungFields}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-foreground-secondary">Infiltrates:</span>
              <span className="font-medium text-foreground-primary">{analysis.lungAnalysis.infiltrates.length || 'None'}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-foreground-secondary">Pleural Effusion:</span>
              <span className="font-medium text-foreground-primary">{analysis.lungAnalysis.pleuralEffusion.length || 'None'}</span>
            </div>
          </div>
        </div>
      </div>

      <div className="bg-background-elevated p-4 rounded-lg border border-border">
        <h5 className="font-medium text-foreground-primary mb-3">Detected Abnormalities</h5>
        <div className="space-y-2">
          {analysis.abnormalities.filter(a => a.present).length === 0 ? (
            <p className="text-green-600 text-sm flex items-center gap-2">
              <CheckCircle size={16} /> No abnormalities detected
            </p>
          ) : (
            analysis.abnormalities.filter(a => a.present).map((abnormality, idx) => (
              <div key={idx} className="flex items-center justify-between p-2 bg-danger-light rounded border border-red-200 dark:border-red-800">
                <div>
                  <span className="font-medium text-red-800 dark:text-red-300 capitalize">{abnormality.type.replace('_', ' ')}</span>
                  <p className="text-xs text-red-600 dark:text-red-400">{abnormality.description}</p>
                </div>
                {renderConfidenceBadge(abnormality.confidence)}
              </div>
            ))
          )}
        </div>
      </div>

      <div className="bg-background-secondary p-4 rounded-lg border border-border">
        <h5 className="font-medium text-foreground-primary mb-3">Recommendations</h5>
        <div className="space-y-2">
          {analysis.recommendations.map((rec, idx) => (
            <div key={idx} className="flex items-start gap-2 text-sm">
              <Info className="text-blue-500 mt-0.5 flex-shrink-0" size={16} />
              <div>
                <span className="font-medium text-foreground-primary">{rec.recommendation}</span>
                <p className="text-foreground-muted text-xs">Timeframe: {rec.timeframe}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );

  const renderCTScanAnalysis = (analysis: CTScanAnalysisResult) => (
    <div className="space-y-4">
      <div className="bg-gradient-to-r from-blue-50 to-indigo-50 dark:from-blue-900/20 dark:to-indigo-900/20 p-4 rounded-lg border border-blue-200 dark:border-blue-800">
        <h4 className="font-semibold text-blue-800 dark:text-blue-300 mb-2">Overall Impression</h4>
        <p className="text-foreground-primary">{analysis.overallImpression}</p>
        <div className="mt-2 flex items-center gap-2">
          {renderConfidenceBadge(analysis.confidence)}
        </div>
      </div>

      <div className="bg-background-elevated p-4 rounded-lg border border-border">
        <h5 className="font-medium text-foreground-primary mb-3">Organ Analysis</h5>
        <div className="grid grid-cols-2 gap-3">
          {analysis.organAnalysis.map((organ, idx) => (
            <div key={idx} className={`p-3 rounded-lg ${organ.status === 'normal' ? 'bg-success-light border border-green-200 dark:border-green-800' : 'bg-danger-light border border-red-200 dark:border-red-800'}`}>
              <div className="flex items-center justify-between mb-1">
                <span className="font-medium text-foreground-primary">{organ.organ}</span>
                <span className={`text-xs px-2 py-0.5 rounded ${organ.status === 'normal' ? 'bg-success-light text-success-dark' : 'bg-danger-light text-danger-dark'}`}>
                  {organ.status}
                </span>
              </div>
              <p className="text-xs text-foreground-secondary">{organ.findings.join(', ')}</p>
            </div>
          ))}
        </div>
      </div>

      <div className="bg-background-elevated p-4 rounded-lg border border-border">
        <h5 className="font-medium text-foreground-primary mb-3">Measurements</h5>
        <div className="space-y-2">
          {analysis.measurements.slice(0, 6).map((measurement, idx) => (
            <div key={idx} className="flex items-center justify-between text-sm p-2 bg-background-secondary rounded">
              <span className="text-foreground-secondary">{measurement.structure} - {measurement.measurement}</span>
              <div className="text-right">
                <span className="font-medium text-foreground-primary">{measurement.value} {measurement.unit}</span>
                <span className={`ml-2 text-xs ${measurement.interpretation === 'Normal' ? 'text-green-600' : 'text-amber-600'}`}>
                  ({measurement.interpretation})
                </span>
              </div>
            </div>
          ))}
        </div>
      </div>

      <div className="bg-background-secondary p-4 rounded-lg border border-border">
        <h5 className="font-medium text-foreground-primary mb-3">Recommendations</h5>
        <div className="space-y-2">
          {analysis.recommendations.map((rec, idx) => (
            <div key={idx} className="flex items-start gap-2 text-sm">
              <Info className="text-blue-500 mt-0.5 flex-shrink-0" size={16} />
              <div>
                <span className="font-medium text-foreground-primary">{rec.recommendation}</span>
                <p className="text-foreground-muted text-xs">Priority: {rec.priority}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );

  const renderMRIAnalysis = (analysis: MRIAnalysisResult) => (
    <div className="space-y-4">
      <div className="bg-gradient-to-r from-purple-50 to-pink-50 dark:from-purple-900/20 dark:to-pink-900/20 p-4 rounded-lg border border-purple-200 dark:border-purple-800">
        <h4 className="font-semibold text-purple-800 dark:text-purple-300 mb-2">Overall Impression</h4>
        <p className="text-foreground-primary">{analysis.overallImpression}</p>
        <div className="mt-2 flex items-center gap-2">
          {renderConfidenceBadge(analysis.confidence)}
        </div>
      </div>

      {analysis.brainAnalysis && (
        <div className="bg-background-elevated p-4 rounded-lg border border-border">
          <h5 className="font-medium text-foreground-primary mb-3 flex items-center gap-2">
            <Brain className="text-purple-500" size={18} />
            Brain Analysis
          </h5>
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <div className="flex justify-between text-sm">
                <span className="text-foreground-secondary">Ventricles:</span>
                <span className="font-medium capitalize text-foreground-primary">{analysis.brainAnalysis.ventricles.size}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-foreground-secondary">White Matter:</span>
                <span className="font-medium capitalize text-foreground-primary">{analysis.brainAnalysis.whiteMatter.status}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-foreground-secondary">Gray Matter:</span>
                <span className="font-medium capitalize text-foreground-primary">{analysis.brainAnalysis.grayMatter.status}</span>
              </div>
            </div>
            <div className="space-y-2">
              <div className="flex justify-between text-sm">
                <span className="text-foreground-secondary">Vascular:</span>
                <span className="font-medium capitalize text-foreground-primary">{analysis.brainAnalysis.vascular.status}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-foreground-secondary">Masses:</span>
                <span className={`font-medium ${analysis.brainAnalysis.masses.present ? 'text-red-600' : 'text-green-600'}`}>
                  {analysis.brainAnalysis.masses.present ? 'Present' : 'None'}
                </span>
              </div>
            </div>
          </div>
        </div>
      )}

      {analysis.spineAnalysis && (
        <div className="bg-background-elevated p-4 rounded-lg border border-border">
          <h5 className="font-medium text-foreground-primary mb-3">Spine Analysis</h5>
          <div className="space-y-3">
            <div className="text-sm">
              <span className="text-foreground-secondary">Vertebral Bodies:</span>
              <span className="ml-2 font-medium capitalize text-foreground-primary">{analysis.spineAnalysis.vertebralBodies.status}</span>
            </div>
            <div className="text-sm">
              <span className="text-foreground-secondary">Spinal Cord:</span>
              <span className="ml-2 font-medium capitalize text-foreground-primary">{analysis.spineAnalysis.spinalCord.status}</span>
            </div>
            <div className="mt-3">
              <h6 className="text-xs font-medium text-foreground-muted mb-2">Disc Status</h6>
              <div className="grid grid-cols-3 gap-2">
                {analysis.spineAnalysis.intervertebralDiscs.slice(0, 5).map((disc, idx) => (
                  <div key={idx} className={`p-2 rounded text-xs ${disc.status === 'normal' ? 'bg-success-light border border-green-200 dark:border-green-800' : 'bg-warning-light border border-amber-200 dark:border-amber-800'}`}>
                    <div className="font-medium text-foreground-primary">{disc.level}</div>
                    <div className="capitalize text-foreground-secondary">{disc.status}</div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      )}

      <div className="bg-background-secondary p-4 rounded-lg border border-border">
        <h5 className="font-medium text-foreground-primary mb-3">Recommendations</h5>
        <div className="space-y-2">
          {analysis.recommendations.map((rec, idx) => (
            <div key={idx} className="flex items-start gap-2 text-sm">
              <Info className="text-purple-500 mt-0.5 flex-shrink-0" size={16} />
              <div>
                <span className="font-medium text-foreground-primary">{rec.recommendation}</span>
                <p className="text-foreground-muted text-xs">Priority: {rec.priority}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );

  const renderMammographyAnalysis = (analysis: MammographyAnalysisResult) => (
    <div className="space-y-4">
      <div className="bg-gradient-to-r from-pink-50 to-rose-50 dark:from-pink-900/20 dark:to-rose-900/20 p-4 rounded-lg border border-pink-200 dark:border-pink-800">
        <div className="flex items-center justify-between mb-2">
          <h4 className="font-semibold text-pink-800 dark:text-pink-300">BI-RADS Assessment</h4>
          <span className={`px-3 py-1 rounded-full text-sm font-bold ${analysis.biRadsAssessment.category === 1 ? 'bg-success-light text-success-dark' :
            analysis.biRadsAssessment.category === 2 ? 'bg-success-light text-success-dark' :
              analysis.biRadsAssessment.category === 3 ? 'bg-warning-light text-warning-dark' :
                analysis.biRadsAssessment.category === 4 ? 'bg-orange-100 dark:bg-orange-900/30 text-orange-700 dark:text-orange-400' :
                  analysis.biRadsAssessment.category === 5 ? 'bg-danger-light text-danger-dark' :
                    'bg-background-tertiary text-foreground-secondary'
            }`}>
            Category {analysis.biRadsAssessment.category}
          </span>
        </div>
        <p className="text-foreground-primary">{analysis.biRadsAssessment.categoryDescription}</p>
        <p className="text-sm text-foreground-secondary mt-2">
          <strong>Probability of Malignancy:</strong> {analysis.biRadsAssessment.probabilityOfMalignancy}
        </p>
        <div className="mt-2 flex items-center gap-2">
          {renderConfidenceBadge(analysis.confidence)}
        </div>
      </div>

      <div className="bg-background-elevated p-4 rounded-lg border border-border">
        <h5 className="font-medium text-foreground-primary mb-3">Breast Density</h5>
        <div className="flex items-center gap-4">
          <div className="flex-1">
            <div className="h-4 bg-background-tertiary rounded-full overflow-hidden">
              <div
                className="h-full bg-pink-500 rounded-full"
                style={{ width: `${analysis.breastDensity.percentage}%` }}
              />
            </div>
          </div>
          <span className="text-sm font-medium text-foreground-primary">{analysis.breastDensity.percentage}%</span>
        </div>
        <p className="text-xs text-foreground-muted mt-2">Category {analysis.breastDensity.category}: {analysis.breastDensity.description}</p>
      </div>

      <div className="grid grid-cols-2 gap-4">
        <div className="bg-background-elevated p-4 rounded-lg border border-border">
          <h5 className="font-medium text-foreground-primary mb-3">Masses</h5>
          {analysis.masses.present ? (
            <div className="space-y-2">
              {analysis.masses.findings.map((mass, idx) => (
                <div key={idx} className="text-sm p-2 bg-warning-light rounded border border-amber-200 dark:border-amber-800">
                  <span className="font-medium text-foreground-primary">{mass.location}</span>
                  <p className="text-xs text-foreground-secondary">{mass.size} - {mass.assessment}</p>
                </div>
              ))}
            </div>
          ) : (
            <p className="text-green-600 text-sm flex items-center gap-2">
              <CheckCircle size={16} /> No masses detected
            </p>
          )}
        </div>

        <div className="bg-background-elevated p-4 rounded-lg border border-border">
          <h5 className="font-medium text-foreground-primary mb-3">Calcifications</h5>
          {analysis.calcifications.present ? (
            <div className="space-y-2">
              {analysis.calcifications.findings.map((calc, idx) => (
                <div key={idx} className="text-sm p-2 bg-warning-light rounded border border-amber-200 dark:border-amber-800">
                  <span className="font-medium text-foreground-primary">{calc.location}</span>
                  <p className="text-xs text-foreground-secondary">{calc.type} - {calc.assessment}</p>
                </div>
              ))}
            </div>
          ) : (
            <p className="text-green-600 text-sm flex items-center gap-2">
              <CheckCircle size={16} /> No suspicious calcifications
            </p>
          )}
        </div>
      </div>

      <div className="bg-background-secondary p-4 rounded-lg border border-border">
        <h5 className="font-medium text-foreground-primary mb-3">Recommendations</h5>
        <div className="space-y-2">
          {analysis.recommendations.map((rec, idx) => (
            <div key={idx} className="flex items-start gap-2 text-sm">
              <Info className="text-pink-500 mt-0.5 flex-shrink-0" size={16} />
              <div>
                <span className="font-medium text-foreground-primary">{rec.recommendation}</span>
                <p className="text-foreground-muted text-xs">Timeframe: {rec.timeframe}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );

  const renderRetinalAnalysis = (analysis: RetinalImagingAnalysisResult) => (
    <div className="space-y-4">
      <div className="bg-gradient-to-r from-amber-50 to-yellow-50 dark:from-amber-900/20 dark:to-yellow-900/20 p-4 rounded-lg border border-amber-200 dark:border-amber-800">
        <h4 className="font-semibold text-amber-800 dark:text-amber-300 mb-2">Overall Impression</h4>
        <p className="text-foreground-primary">{analysis.overallImpression}</p>
        <div className="mt-2 flex items-center gap-2">
          {renderConfidenceBadge(analysis.confidence)}
        </div>
      </div>

      {analysis.diabeticRetinopathyAnalysis && (
        <div className="bg-background-elevated p-4 rounded-lg border border-border">
          <h5 className="font-medium text-foreground-primary mb-3 flex items-center gap-2">
            <EyeIcon className="text-amber-500" size={18} />
            Diabetic Retinopathy Assessment
          </h5>
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <div className="flex justify-between text-sm">
                <span className="text-foreground-secondary">Present:</span>
                <span className={`font-medium ${analysis.diabeticRetinopathyAnalysis.present ? 'text-red-600' : 'text-green-600'}`}>
                  {analysis.diabeticRetinopathyAnalysis.present ? 'Yes' : 'No'}
                </span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-foreground-secondary">Severity:</span>
                <span className="font-medium capitalize text-foreground-primary">{analysis.diabeticRetinopathyAnalysis.severity.replace('_', ' ')}</span>
              </div>
            </div>
            <div className="space-y-2">
              <div className="flex justify-between text-sm">
                <span className="text-foreground-secondary">Microaneurysms:</span>
                <span className="font-medium text-foreground-primary">{analysis.diabeticRetinopathyAnalysis.microaneurysms.count}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-foreground-secondary">DME:</span>
                <span className={`font-medium ${analysis.diabeticRetinopathyAnalysis.dme.present ? 'text-amber-600' : 'text-green-600'}`}>
                  {analysis.diabeticRetinopathyAnalysis.dme.present ? 'Present' : 'Absent'}
                </span>
              </div>
            </div>
          </div>
        </div>
      )}

      {analysis.glaucomaAnalysis && (
        <div className="bg-background-elevated p-4 rounded-lg border border-border">
          <h5 className="font-medium text-foreground-primary mb-3">Glaucoma Risk Assessment</h5>
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <div className="flex justify-between text-sm">
                <span className="text-foreground-secondary">Risk Level:</span>
                <span className={`font-medium capitalize ${analysis.glaucomaAnalysis.riskLevel === 'low' ? 'text-green-600' :
                  analysis.glaucomaAnalysis.riskLevel === 'moderate' ? 'text-amber-600' :
                    'text-red-600'
                  }`}>
                  {analysis.glaucomaAnalysis.riskLevel}
                </span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-foreground-secondary">Cup/Disc Ratio:</span>
                <span className="font-medium text-foreground-primary">{analysis.glaucomaAnalysis.cupToDiscRatio.vertical}</span>
              </div>
            </div>
            <div className="space-y-2">
              <div className="flex justify-between text-sm">
                <span className="text-foreground-secondary">NFL Status:</span>
                <span className="font-medium capitalize text-foreground-primary">{analysis.glaucomaAnalysis.nerveFiberLayer.status}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-foreground-secondary">Notching:</span>
                <span className={`font-medium ${analysis.glaucomaAnalysis.opticDisc.notching ? 'text-red-600' : 'text-green-600'}`}>
                  {analysis.glaucomaAnalysis.opticDisc.notching ? 'Present' : 'None'}
                </span>
              </div>
            </div>
          </div>
        </div>
      )}

      {analysis.amdAnalysis && (
        <div className="bg-background-elevated p-4 rounded-lg border border-border">
          <h5 className="font-medium text-foreground-primary mb-3">AMD Assessment</h5>
          <div className="space-y-2 text-sm">
            <div className="flex justify-between">
              <span className="text-foreground-secondary">AMD Present:</span>
              <span className={`font-medium ${analysis.amdAnalysis.present ? 'text-amber-600' : 'text-green-600'}`}>
                {analysis.amdAnalysis.present ? 'Yes' : 'No'}
              </span>
            </div>
            <div className="flex justify-between">
              <span className="text-foreground-secondary">Type:</span>
              <span className="font-medium capitalize text-foreground-primary">{analysis.amdAnalysis.type.replace('_', ' ')}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-foreground-secondary">Drusen Present:</span>
              <span className="font-medium text-foreground-primary">{analysis.amdAnalysis.drusen.present ? 'Yes' : 'No'}</span>
            </div>
          </div>
        </div>
      )}

      <div className="bg-background-secondary p-4 rounded-lg border border-border">
        <h5 className="font-medium text-foreground-primary mb-3">Recommendations</h5>
        <div className="space-y-2">
          {analysis.recommendations.map((rec, idx) => (
            <div key={idx} className="flex items-start gap-2 text-sm">
              <Info className="text-amber-500 mt-0.5 flex-shrink-0" size={16} />
              <div>
                <span className="font-medium text-foreground-primary">{rec.recommendation}</span>
                <p className="text-foreground-muted text-xs">Timeframe: {rec.timeframe}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );

  const renderAIAnalysis = () => {
    if (aiLoading) {
      return (
        <div className="flex flex-col items-center justify-center py-12">
          <Loader2 className="animate-spin text-teal-500 mb-4" size={48} />
          <p className="text-foreground-secondary font-medium">Running AI Analysis...</p>
          <p className="text-foreground-muted text-sm">This may take a moment</p>
        </div>
      );
    }

    if (!aiAnalysis) {
      return (
        <div className="text-center py-12">
          <AlertTriangle className="text-amber-500 mx-auto mb-4" size={48} />
          <p className="text-foreground-secondary">Unable to perform AI analysis</p>
        </div>
      );
    }

    switch (selectedScan?.modality) {
      case 'X-Ray':
        return renderChestXRayAnalysis(aiAnalysis as ChestXRayAnalysisResult);
      case 'CT Scan':
        return renderCTScanAnalysis(aiAnalysis as CTScanAnalysisResult);
      case 'MRI':
        return renderMRIAnalysis(aiAnalysis as MRIAnalysisResult);
      case 'Mammography':
        return renderMammographyAnalysis(aiAnalysis as MammographyAnalysisResult);
      case 'Retinal':
        return renderRetinalAnalysis(aiAnalysis as RetinalImagingAnalysisResult);
      default:
        return <p className="text-foreground-secondary">AI analysis not available for this modality</p>;
    }
  };

  return (
    <div className="space-y-6 animate-fade-in">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-bold text-foreground-primary">Radiology & PACS</h1>
          <p className="text-foreground-muted">Diagnostic imaging workflow and AI-powered analysis.</p>
        </div>
        <button
          className="bg-teal-600 text-white px-4 py-2 rounded-lg flex items-center gap-2 hover:bg-teal-700 theme-transition shadow-lg shadow-teal-600/20"
        >
          <Plus size={18} /> Schedule Scan
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
        <div className="bg-background-elevated p-6 rounded-xl border border-border shadow-sm">
          <div className="flex items-center gap-4">
            <div className="p-3 bg-indigo-100 dark:bg-indigo-900/30 text-indigo-600 dark:text-indigo-400 rounded-lg"><Scan size={24} /></div>
            <div>
              <p className="text-sm text-foreground-muted font-medium">Total Scans</p>
              <h3 className="text-2xl font-bold text-foreground-primary">45</h3>
            </div>
          </div>
        </div>
        <div className="bg-background-elevated p-6 rounded-xl border border-border shadow-sm">
          <div className="flex items-center gap-4">
            <div className="p-3 bg-teal-100 dark:bg-teal-900/30 text-teal-600 dark:text-teal-400 rounded-lg"><Brain size={24} /></div>
            <div>
              <p className="text-sm text-foreground-muted font-medium">AI Analyzed</p>
              <h3 className="text-2xl font-bold text-foreground-primary">32</h3>
            </div>
          </div>
        </div>
        <div className="bg-background-elevated p-6 rounded-xl border border-border shadow-sm">
          <div className="flex items-center gap-4">
            <div className="p-3 bg-amber-100 dark:bg-amber-900/30 text-amber-600 dark:text-amber-400 rounded-lg"><AlertTriangle size={24} /></div>
            <div>
              <p className="text-sm text-foreground-muted font-medium">Pending Review</p>
              <h3 className="text-2xl font-bold text-foreground-primary">8</h3>
            </div>
          </div>
        </div>
        <div className="bg-background-elevated p-6 rounded-xl border border-border shadow-sm">
          <div className="flex items-center gap-4">
            <div className="p-3 bg-green-100 dark:bg-green-900/30 text-green-600 dark:text-green-400 rounded-lg"><CheckCircle size={24} /></div>
            <div>
              <p className="text-sm text-foreground-muted font-medium">Finalized Today</p>
              <h3 className="text-2xl font-bold text-foreground-primary">12</h3>
            </div>
          </div>
        </div>
      </div>

      <div className="bg-background-elevated rounded-xl border border-border shadow-sm overflow-hidden">
        <div className="p-4 border-b border-border flex gap-4">
          <div className="relative flex-1">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-foreground-muted" size={20} />
            <input type="text" placeholder="Search PACS..." className="w-full pl-10 pr-4 py-2 border border-border rounded-lg outline-none focus:ring-2 focus:ring-teal-500 bg-background-secondary text-foreground-primary placeholder:text-foreground-muted" />
          </div>
        </div>
        <table className="w-full text-left">
          <thead className="bg-background-secondary border-b border-border">
            <tr>
              <th className="px-6 py-4 font-semibold text-foreground-primary">Accession #</th>
              <th className="px-6 py-4 font-semibold text-foreground-primary">Patient</th>
              <th className="px-6 py-4 font-semibold text-foreground-primary">Modality</th>
              <th className="px-6 py-4 font-semibold text-foreground-primary">Images</th>
              <th className="px-6 py-4 font-semibold text-foreground-primary">Status</th>
              <th className="px-6 py-4 font-semibold text-foreground-primary">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-border">
            {requests.map((req) => (
              <tr key={req.id} className="hover:bg-background-secondary theme-transition">
                <td className="px-6 py-4 font-mono text-foreground-secondary text-sm">{req.id}</td>
                <td className="px-6 py-4 font-medium text-foreground-primary">
                  {req.patientName}
                  <p className="text-xs text-foreground-muted">{req.doctor}</p>
                </td>
                <td className="px-6 py-4 text-foreground-secondary">
                  <div className="flex items-center gap-2">
                    {getModalityIcon(req.modality)}
                    <div>
                      <span className="font-bold">{req.modality}</span>
                      <p className="text-xs">{req.bodyPart}</p>
                    </div>
                  </div>
                </td>
                <td className="px-6 py-4 text-foreground-secondary flex items-center gap-1">
                  <Image size={14} /> {req.imageCount}
                </td>
                <td className="px-6 py-4">
                  <span className={`px-2 py-1 rounded-full text-xs font-medium ${getStatusColor(req.status)}`}>
                    {req.status}
                  </span>
                </td>
                <td className="px-6 py-4 flex gap-2">
                  {req.status !== 'Scheduled' && (
                    <button
                      onClick={() => openViewer(req)}
                      className="text-teal-600 dark:text-teal-400 hover:text-teal-800 dark:hover:text-teal-300 text-sm font-medium flex items-center gap-1 bg-teal-50 dark:bg-teal-900/30 px-2 py-1 rounded theme-transition"
                    >
                      <Eye size={16} /> View
                    </button>
                  )}
                  {req.status === 'Finalized' && (
                    <button className="text-blue-600 dark:text-blue-400 hover:text-blue-800 dark:hover:text-blue-300 text-sm font-medium flex items-center gap-1 bg-blue-50 dark:bg-blue-900/30 px-2 py-1 rounded theme-transition">
                      <FileText size={16} /> Report
                    </button>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* PACS Viewer Modal with AI Analysis */}
      {showViewer && selectedScan && (
        <div className="fixed inset-0 bg-black z-[60] flex flex-col animate-fade-in">
          <div className="h-14 bg-background-elevated flex items-center justify-between px-4 text-foreground-secondary border-b border-border">
            <div className="flex items-center gap-4">
              {getModalityIcon(selectedScan.modality)}
              <div>
                <h3 className="font-bold text-foreground-primary text-sm">{selectedScan.patientName}</h3>
                <p className="text-xs text-foreground-muted">{selectedScan.id} â€¢ {selectedScan.modality} {selectedScan.bodyPart}</p>
              </div>
            </div>
            <div className="flex items-center gap-4">
              {/* Tab buttons */}
              <div className="flex bg-background-secondary rounded-lg p-1">
                <button
                  onClick={() => setActiveTab('viewer')}
                  className={`px-3 py-1 rounded text-sm font-medium theme-transition ${activeTab === 'viewer' ? 'bg-teal-600 text-white' : 'text-foreground-muted hover:text-foreground-primary'}`}
                >
                  <Image size={16} className="inline mr-1" /> Viewer
                </button>
                <button
                  onClick={() => setActiveTab('ai')}
                  className={`px-3 py-1 rounded text-sm font-medium theme-transition flex items-center gap-1 ${activeTab === 'ai' ? 'bg-teal-600 text-white' : 'text-foreground-muted hover:text-foreground-primary'}`}
                >
                  <Brain size={16} /> AI Analysis
                  {aiAnalysis && <span className="w-2 h-2 bg-green-400 rounded-full ml-1" />}
                </button>
              </div>
              <button type="button" className="hover:text-foreground-primary theme-transition" aria-label="Upload image"><Upload size={20} /></button>
              <button className="hover:text-foreground-primary theme-transition" onClick={() => setShowViewer(false)}><X size={24} /></button>
            </div>
          </div>

          {activeTab === 'viewer' ? (
            <div className="flex-1 bg-black flex items-center justify-center relative">
              <div className="text-foreground-muted flex flex-col items-center">
                <Image size={64} className="mb-4 opacity-20" />
                <p>DICOM Viewer Simulation</p>
                <p className="text-sm opacity-50">Image rendering area</p>
              </div>
              {/* Overlay details */}
              <div className="absolute top-4 left-4 text-teal-500 font-mono text-xs">
                <p>W: 255 L: 127</p>
                <p>Zoom: 100%</p>
              </div>

              {/* AI Analysis Button */}
              <button
                onClick={runAIAnalysis}
                disabled={aiLoading}
                className="absolute bottom-4 right-4 bg-gradient-to-r from-teal-500 to-cyan-500 text-white px-4 py-2 rounded-lg flex items-center gap-2 hover:from-teal-600 hover:to-cyan-600 theme-transition shadow-lg disabled:opacity-50"
              >
                {aiLoading ? (
                  <>
                    <Loader2 className="animate-spin" size={18} />
                    Analyzing...
                  </>
                ) : (
                  <>
                    <Brain size={18} />
                    Run AI Analysis
                  </>
                )}
              </button>
            </div>
          ) : (
            <div className="flex-1 bg-background-primary overflow-auto p-6">
              <div className="max-w-4xl mx-auto">
                <div className="flex items-center gap-2 mb-4">
                  <div className="p-2 bg-gradient-to-r from-teal-500 to-cyan-500 rounded-lg">
                    <Brain className="text-white" size={20} />
                  </div>
                  <div>
                    <h3 className="text-foreground-primary font-semibold">AI-Powered Analysis</h3>
                    <p className="text-foreground-muted text-xs">{selectedScan.modality} â€¢ {selectedScan.bodyPart}</p>
                  </div>
                  {aiAnalysis && (
                    <span className="ml-auto px-2 py-1 bg-teal-500/20 text-teal-400 text-xs rounded-full flex items-center gap-1">
                      <span className="w-2 h-2 bg-teal-400 rounded-full animate-pulse" />
                      Analysis Complete
                    </span>
                  )}
                </div>

                {renderAIAnalysis()}

                <div className="mt-4 p-3 bg-background-secondary rounded-lg border border-border">
                  <p className="text-xs text-foreground-muted flex items-start gap-2">
                    <AlertTriangle size={14} className="flex-shrink-0 mt-0.5" />
                    <span>
                      <strong>Disclaimer:</strong> This AI analysis is for educational purposes only and should not replace professional medical interpretation.
                      All findings should be verified by a qualified radiologist and correlated clinically.
                    </span>
                  </p>
                </div>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
};

export default Radiology;
